name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - jan-tennert
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: latest-version
    attributes:
      label: General Info
      options:
        - label: I installed the latest version of SupaCompose
          required: true
        - label: I checked for similar feature requests
          required: true
  - type: textarea
    id: code
    attributes:
      label: What happened? (include your code)
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which Platform did you use?
      options:
        - Desktop
        - Android
        - Web
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of SupaCompose did you use?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
