name: Build demo

on:
  push:
    branches:
      - 'master'
      - 'development'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      working-directory: ./demos/chat-demo-mpp
      run: chmod +x gradlew
    - name: Build demo
      working-directory: ./demos/chat-demo-mpp
      run: ./gradlew build --stacktrace
