name: Analyze code using detekt

on:
  push:
    branches:
      - 'master'
      - 'development'
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Analyze code using detekt
        run: ./gradlew detektAll --stacktrace
