name: Analyze code using detekt

on:
  push:
    branches:
      - 'master'
      - 'development'
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      KONAN_DATA_DIR: ~/.gradle/kotlinNative
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: true
          gradle-home-cache-includes: kotlinNative
      - name: Analyze code using detekt
        run: ./gradlew detektAll --stacktrace --configuration-cache