name: Test project

on:
  push:
    branches:
      - 'master'
      - 'development'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        command: [
          'jvmTest testDebugUnitTest testReleaseUnitTest',
          'jsTest',
          'iosX64Test iosSimulatorArm64Test',
          'macosArm64Test macosX64Test',
          'tvosX64Test tvosSimulatorArm64Test',
          'watchosX64Test watchosSimulatorArm64Test',
          'mingwX64Test',
        ]
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Test supabase-kt
        run: ./gradlew {{ matrix.command }} --stacktrace
