name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for gradlew (demo)
      run: chmod +x demos/chat-demo-mpp/gradlew
    - name: Build supabase-kt
      run: ./gradlew build test --stacktrace
    - name: Build demo
      run: ./demos/chat-demo-mpp/gradlew build test --stacktrace
